#! /bin/bash

# Author: Mohammed Albatati
# Date: 20 Oct 2021
# sync the sever by folder instead of syncing all the folders all at once

RED='\033[0;31m'
NC='\033[0m' # No Color

set -e
# Ensure the asset csv file is available and if not then create it 
# [ ! -f "/tmp/folders.txt" ] && echo 'File not available at temp directory  Creating a new folders file' && ls "/Volumes/MPro_FIles/KIU-WTC/KIU SWT" > "/tmp/folders.txt" && echo "File created successfully"

mounting(){
    echo "Make sure to create three drives with cfdisk command sda1 512M and sda2 2G and sda3 no need to change the types"
    echo "START MOUNTING THE DRIVES"
    mkswap /dev/sda2
    sleep 2
    swapon /dev/sda2
    sleep 2
    mkfs.vfat /dev/sda1
    sleep 2
    mkfs.ext4 /dev/sda3
    sleep 2
    mount /dev/sda3 /mnt
    mkdir -p /mnt/boot
    sleep 2
    mount /dev/sda1 /mnt/boot
    sleep 2
    echo "mounting finished"
    sleep 2
    lsblk
    echo "Now move to the next stage of installing arch"
}

installing_arch_pacstrp(){
    pacstrap -i /mnt base base-devel linux linux-firmware vim
    echo "Installing the packages"
    sleep 2
    genfstab -U -p /mnt >> /mnt/etc/fstab
    cat /mnt/etc/fstab
    echo "Please next command use arch-chroot"
    echo "Download the git folder "
    echo "go to the next stage of configuration"
}

configuration(){
    echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
    echo "LANG=en_US.UTF-8" >> /etc/locale.conf
    locale-gen
    export LANG=en_US.UTF-8
    sleep 1
    ln -s /usr/share/zoneinfo/Asia/Baghdad /etc/localtime
    hwclock --systohc
    echo "go to the next stage of user creation"
}

user(){
    echo "mohammed" > /etc/hostname
    sleep 1
    pacman -Syu sudo bash-completion networkmanager
    sleep 1
    useradd -m -g users -G wheel,storage,power,log -s /bin/bash mohammed
    sleep 1
    echo "change the sudo password"
    passwd
    echo "change the user password"
    passwd mohammed
    systemctl enable NetworkManager
    echo "Use this command to edit the wheel (EDITOR=nano visudo)"
}

bootloader(){
    mkinitcpio -p linux
    pacman -S grub
    grub-install /dev/sda
    grub-mkconfig -o /boot/grub/grub.cfg
    echo "You can exit now and unmount then reboot"
}


echo "What type of sync you need:"
read -p "1-Mounting, 2-Install pacstrap, 3-Configuration 4-user 5-install the bootloader: " num
echo "==========="
case $num in 
  1) mounting;;
  2) installing_arch_pacstrp;;
  3) configuration;;
  4) user;;
  5) bootloader;;
  *) echo "Wrong selection";;
esac


