#! /bin/bash

# Author: Mohammed Albatati
# Date: 20 Oct 2021
# sync the sever by folder instead of syncing all the folders all at once

RED='\033[0;31m'
NC='\033[0m' # No Color

set -e
# Ensure the asset csv file is available and if not then create it 
# [ ! -f "/tmp/folders.txt" ] && echo 'File not available at temp directory  Creating a new folders file' && ls "/Volumes/MPro_FIles/KIU-WTC/KIU SWT" > "/tmp/folders.txt" && echo "File created successfully"

mounting(){
    mkswap /dev/sda2
    sleep 2
    swapon /dev/sda2
    sleep 2
    mkfs.vfat /dev/sda1
    sleep 2
    mkfs.ext4 /dev/sda3
    sleep 2
    mount /dev/sda3 /mnt
    mkdir -p /mnt/boot
    sleep 2
    mount /dev/sda1 /mnt/boot
    sleep 2
    echo "mounting finished"
    sleep 2
    lsblk
}

installing_arch_pacstrp(){
    pacstrap -i /mnt base base-devel linux linux-firmware vim
    echo "Installing the packages"
    sleep 5
    genfstab -U -p /mnt >> /mnt/etc/fstab
    cat /mnt/etc/fstab
    echo "Please next command use arch-chroot"
}

configuration(){
    echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
    echo "LANG=en_US.UTF-8" >> /etc/locale.conf
    locale-gen
    export LANG=en_US.UTF-8
    sleep 1
    ln -s /usr/share/zoneinfo/Asia/Baghdad /etc/localtime
    hwclock --systohc
}

user(){
    echo "mohammed" > /etc/hostname
    sleep 1
    pacman -Syu sudo bash-completion networkmanager
    sleep 1
    useradd -m -g users -G wheel,storage,power,log -s /bin/bash mohammed
    sleep 1
    echo "change the sudo password"
    passwd
    echo "change the user password"
    passwd mohammed
    systemctl enable NetworkManager
    echo "Use this command to edit the wheelEDITOR=nano visudo"
}

echo "What type of sync you need:"
read -p "1-Mounting, 2-Install pacstrap, 3-Configuration : " num
echo "==========="
case $num in 
  1) mounting;;
  2) installing_arch_pacstrp;;
  3) configuration;;
  4) user;;
  *) echo "Wrong selection";;
esac


