#! /bin/bash

# Author: Mohammed Albatati
# Date: 20 Oct 2021
# sync the sever by folder instead of syncing all the folders all at once

RED='\033[0;31m'
NC='\033[0m' # No Color

set -e
# Ensure the asset csv file is available and if not then create it 
[ ! -f "/tmp/folders.txt" ] && echo 'File not available at temp directory  Creating a new folders file' && ls "/Volumes/MPro_FIles/KIU-WTC/KIU SWT" > "/tmp/folders.txt" && echo "File created successfully"

byEquipment(){
	fzfEquipment=`awk -F"," '{print $1}' "/tmp/folders.txt" | fzf`
    echo -e "Syncing the folder ${RED}$fzfEquipment${NC}"
    echo $fzfEquipment
	# rsync -av --progress "/Volumes/MPro_FIles/KIU-WTC/KIU SWT/$fzfEquipment"  "/Volumes/My Passport for Mac/KIU Equipement/Dubai Server/KIU-WTC/KIU SWT/"
}

by_quipment_multi(){
	fzfEquipment=`awk -F"," '{print $1}' "/tmp/folders.txt" | fzf -m`
    # for element in "${fzfEquipment[*]}" // Use this one
    for element in "${fzfEquipment[@]}"
    do
        # echo -e "Syncing the folder ${RED}$element[*]${NC}"
        echo "End sync ${element[*]}"
        # echo "${element[*]}"
        # echo ${element[*]}
        # echo $fzfEquipment
        # rsync -av --progress "/Volumes/MPro_FIles/KIU-WTC/KIU SWT/$equipement"  "/Volumes/My Passport for Mac/KIU Equipement/Dubai Server/KIU-WTC/KIU SWT/"
        
        # folder="${element[@]}" // use this one 

        # folder="${element}"
        # folder="${element}"
        # echo -e "Syncing the folder ${RED}$folder${NC}"
        # echo "Start sync $folder"
        # echo "Start sync $folder"
        # rsync -av --progress "/Volumes/MPro_FIles/KIU-WTC/KIU SWT/$folder"  "/Volumes/My Passport for Mac/KIU Equipement/Dubai Server/KIU-WTC/KIU SWT/" 
        # echo "End sync $folder"
    done
}

allEquipment(){
    echo "Syncing all folders"
	rsync -av --ignore-existing --progress /Volumes/MPro_FIles/KIU-WTC/KIU\ SWT /Volumes/My\ Passport\ for\ Mac/KIU\ Equipement/Dubai\ Server/KIU-WTC
}

echo "What type of sync you need:"
read -p "1-By folder , 2-All , 3-Multi select : " num
echo "==========="
case $num in 
  1) byEquipment;;
  2) allEquipment;;
  3) by_quipment_multi;;
  *) echo "Wrong selection";;
esac


