#! /bin/bash

# Author: Mohammed Albatati
# Date: 20 Oct 2021
# sync the sever by folder instead of syncing all the folders all at once

set -e
# Ensure the asset csv file is available and if not then create it 
[ ! -f "/tmp/folders.txt" ] && echo 'File not available at temp directory  Creating a new folders file' && ls "/Volumes/MPro_FIles/KIU-WTC/KIU SWT" > "/tmp/folders.txt" && echo "File created successfully"

byEquipment(){
	fzfEquipment=`awk -F"," '{print $1}' "/tmp/folders.txt" | fzf`
	rsync -av --progress "/Volumes/MPro_FIles/KIU-WTC/KIU SWT/$fzfEquipment"  "/Volumes/My Passport for Mac/KIU Equipement/Dubai Server/KIU-WTC/KIU SWT/"
}

allEquipment(){
	rsync -av --ignore-existing --progress /Volumes/MPro_FIles/KIU-WTC/KIU\ SWT /Volumes/My\ Passport\ for\ Mac/KIU\ Equipement/Dubai\ Server/KIU-WTC
}

echo "What type of sync you need:"
read -p "1-By folder or 2-All : " num
echo "==========="
case $num in 
  1) byEquipment;;
  2) allEquipment;;
  *) echo "Wrong selection";;
esac


