#! /bin/bash

# Author Mohammed Albatati
# Date created: 23 Nov 21
# Description: This script takes the the files from the download folder and moves it to the org images folder so its eassy to link

# Requirements: down the files and put them in the Download folder

# Adding color to the text
color=`tput setaf 1`
reset=`tput sgr0`
# Selecting the file
echo "Select ${color}file ${reset}"
sleep 2
find ~/Downloads -maxdepth 1 -type f -name "*" | fzf --height=10% --border='vertical'| xargs -I{} cp {} ~/org/images/
