#! /usr/bin/env bash
source /usr/local/bin/bash_colors.sh

# Date: 20260210
# This will be a main function I'll use it to call other functions for the NEOS
# bash scripts I made so far


function find-sqb() {
    local sqb_dir="/Volumes/WL-SL/02 Slickline/01 Jobs/BECL BP/SQB/"
    # Check if the directory available or not!
    if [[ ! -d "${sqb_dir}"  ]]; then
        echo -e "${RED}Folder SQB not available${NC}"
        exit 1
    fi
    # TODO: make the find sqb in a separeate file and but in /local/bin
    # TODO: make the sqb accept multiple arg like ./neos_tree_daily_reports 
    # Check if the user passed an arg or not
    if [ $# -eq 0 ]; then
       echo "Enter well name to search its SQB:" 
       read -r well
       [[ -z "$well" ]] && { echo -e "${RED}No well entered.${NC}"; exit 1; }
    else
       well="$1" 
    fi
    local results
    results=$(find "$sqb_dir" -type f -name "*${well}*" 2>/dev/null)
    if [[ -n  "$results" ]]; then
        printf "%s\n" "$results"
    else
        echo -e "${RED}No results found for '$well'${NC}"
    fi
}

function depth_loop() {
    find . -type f -name "*.csv" -exec neos_goes_depth {} \;
}

function sgs_max_val_loop() {
    find . -type f -name "*.txt" -exec neos_sgs_max_values {} \;
}

function export_database() {
   sqlite3 -header -csv "$HOME/org/neosdatabase.db" "SELECT * FROM sl_equipment;" > ~/org/Exported_database_2026_noes.csv
   sqlite3 -header -csv "$HOME/org/neosdatabase.db" "SELECT * FROM personnel_sl;" > ~/org/Exported_database_2026_noes_personnel.csv

   if [[ $? -eq 0 ]]; then
       echo -e "${CYAN}Database exported to CSV${NC}"
   else
       echo -e "${RED}Database export FAILED${NC}" >&2
   fi 
}

function find-no-rqc() {
    local path1="/Volumes/WL-SL/02 Slickline/01 Jobs/BECL BP/Unit1/Daily Report/2026/"
    local path2="/Volumes/WL-SL/02 Slickline/01 Jobs/BECL BP/Unit2/Daily Report/2026/"
    u1=$(find "${path1}" -type f -name "No-*.xlsx" -depth 2 -exec dirname {} \;)
    u2=$(find "${path2}" -type f -name "No-*.xlsx" -depth 2 -exec dirname {} \;)
    echo -e "${GREEN}=========Unit-1 NO-RQC==========\n${u1}${NC}"
    echo -e "${YELLOW}=========Unit-2 NO-RQC==========\n${u2}${NC}"
}

function make-all() {
    cd "$HOME/Desktop/html_generator/"
    make all
}

function asset-register-update() {
    export_database
    cd "~/Desktop/html_generator/html_asset_register/"
    make run-all
}

# while true; do
echo -e "\nChoose:
    tree  - Reports Tree,                 Args   'R-127' etc
    rep   - Un-submitted reports,         Nan
    sgs   - SGS max loop,                 Nan    will loop
    dp    - GOES Depth loop,              Nan    will loop
    sqb   - Find SQB,                     Args   R-338 etc
    sync  - rsync server,                 Nan
    rqc   - Find No-RQC reports           Nan
    1     - fzf Asset,                    Nan
    4     - Copy array of files,          Fill   ~/Downloads/list_of_asset_array.txt
    7     - Check database,               Fill   ~/Downloads/check_asset_exist.txt
    10    - Sweeb expired files           Args   [-m|-d] 20251210 ./
    99    - Make all html                 Nan
    expo  - Export database               Nan
    q     - Quit"
read -p "Select: " num
echo "================================="

case $num in
    tree) neos_tree_reports "$@";;
    1) neosfzf "$@";;
    rep) check_missing_reports;;
    expo) export_database;;
    4) neos_array_copy;;
    sgs) sgs_max_val_loop;;
    dp) depth_loop;;
    7) neos_check_asset_in_database;;
    sqb) find-sqb "$@";;
    sync) server_rsync;;
    # regis) asset-register-update;;
    10) sweeb_expired_files "$@";;
    99) make-all;; 
    rqc) find-no-rqc;;
    q|Q) echo "Goodby"; break;;
    *) echo -e "${RED}Wrong selection${NC}";;
esac
# done
