#! /usr/bin/env bash
source /usr/local/bin/bash_colors.sh

# Date: 20260210
# This will be a main function I'll use it to call other functions for the NEOS
# bash scripts I made so far


echo -e "Choose:
1-Reports Tree,                 Args   'R-127' etc
2-fzf Asset,                    Nan
3-Un-submitted reports,         Nan
4-Copy array of files,          Fill   ~/Downloads/list_of_asset_array.txt
5-GOES Depth,                   Args   select files
6-GOES Depth loop,              Nan    will loop
7-Check database,               Fill   ~/Downloads/check_asset_exist.txt
8-Find SQB,                     Args   R-338 etc
9-rsync server,                 Nan
10-Sweeb expired files          Args   [-m|-d] 20251210 ./
99-Make all html                Nan
12-Find No-RQC reports          Nan"
read -p "Select: " num
echo "================================="

function find-sqb() {
    if [[ ! -d "/Volumes/WL-SL/02 Slickline/01 Jobs/BECL BP/SQB/"  ]]; then
        echo -e "${RED}Folder SQB not available${NC}"
        exit 1
    fi
    results=$(find "/Volumes/WL-SL/02 Slickline/01 Jobs/BECL BP/SQB/" -type f -name "*$1*")
    if [[ -n  results ]]; then
        printf "$results\n"
        # echo $results
    else
        echo -e "${RED}No results found${NC}"
    fi
}

function depth_loop() {
    find . -type f -name "*.csv" -exec neos_goes_depth {} \;
}

function find-no-rqc() {
    local path1="/Volumes/WL-SL/02 Slickline/01 Jobs/BECL BP/Unit1/Daily Report/2026/"
    local path2="/Volumes/WL-SL/02 Slickline/01 Jobs/BECL BP/Unit2/Daily Report/2026/"
    u1=$(find "${path1}" -type f -name "No-*.xlsx" -depth 2 -exec dirname {} \;)
    u2=$(find "${path2}" -type f -name "No-*.xlsx" -depth 2 -exec dirname {} \;)
    echo -e "${GREEN}=========Unit-1 NO-RQC==========\n${u1}${NC}"
    echo -e "${YELLOW}=========Unit-2 NO-RQC==========\n${u2}${NC}"
}

function make-all() {
    cd "$HOME/Desktop/html_generator/"
    make all
}

case $num in
  1) neos_tree_reports "$@";;
  2) neosfzf "$@";;
  3) check_missing_reports;;
  4) neos_array_copy;;
  5) neos_goes_depth "$@";;
  6) depth_loop;;
  7) neos_check_asset_in_database;;
  8) find-sqb "$@";;
  9) server_rsync;;
  10) sweeb_expired_files "$@";;
  99) make-all;;
  12) find-no-rqc;;
  *) echo "Wrong selection";;
esac
