#! /usr/bin/env bash
source /usr/local/bin/bash_colors.sh

# Date: 20260210
# This will be a main function I'll use it to call other functions for the NEOS
# bash scripts I made so far


echo -e "Choose:
tree  - Reports Tree,                 Args   'R-127' etc
2     - fzf Asset,                    Nan
rep   - Un-submitted reports,         Nan
4     - Copy array of files,          Fill   ~/Downloads/list_of_asset_array.txt
dp    - GOES Depth,                   Args   select files
dpl   - GOES Depth loop,              Nan    will loop
7     - Check database,               Fill   ~/Downloads/check_asset_exist.txt
sqb   - Find SQB,                     Args   R-338 etc
sync  - rsync server,                 Nan
10    - Sweeb expired files           Args   [-m|-d] 20251210 ./
99    - Make all html                 Nan
rqc   - Find No-RQC reports           Nan"
read -p "Select: " num
echo "================================="

function find-sqb() {
    local sqb_dir="/Volumes/WL-SL/02 Slickline/01 Jobs/BECL BP/SQB/"
    # Check if the directory available or not!
    if [[ ! -d "${sqb_dir}"  ]]; then
        echo -e "${RED}Folder SQB not available${NC}"
        exit 1
    fi
    # TODO: make the find sqb in a separeate file and but in /local/bin
    # TODO: make the sqb accept multiple arg like ./neos_tree_daily_reports 
    # Check if the user passed an arg or not
    if [ $# -eq 0 ]; then
       echo "Enter well name to search its SQB:" 
       read -r well
       [[ -z "$well" ]] && { echo -e "${RED}No well entered.${NC}"; exit 1; }
    else
       well="$1" 
    fi
    local results
    results=$(find "$sqb_dir" -type f -name "*${well}*" 2>/dev/null)
    if [[ -n  "$results" ]]; then
        printf "%s\n" "$results"
    else
        echo -e "${RED}No results found for '$well'${NC}"
    fi
}

function depth_loop() {
    find . -type f -name "*.csv" -exec neos_goes_depth {} \;
}

function find-no-rqc() {
    local path1="/Volumes/WL-SL/02 Slickline/01 Jobs/BECL BP/Unit1/Daily Report/2026/"
    local path2="/Volumes/WL-SL/02 Slickline/01 Jobs/BECL BP/Unit2/Daily Report/2026/"
    u1=$(find "${path1}" -type f -name "No-*.xlsx" -depth 2 -exec dirname {} \;)
    u2=$(find "${path2}" -type f -name "No-*.xlsx" -depth 2 -exec dirname {} \;)
    echo -e "${GREEN}=========Unit-1 NO-RQC==========\n${u1}${NC}"
    echo -e "${YELLOW}=========Unit-2 NO-RQC==========\n${u2}${NC}"
}

function make-all() {
    cd "$HOME/Desktop/html_generator/"
    make all
}

case $num in
  tree) neos_tree_reports "$@";;
  2) neosfzf "$@";;
  rep) check_missing_reports;;
  4) neos_array_copy;;
  dp) neos_goes_depth "$@";;
  dpl) depth_loop;;
  7) neos_check_asset_in_database;;
  sqb) find-sqb "$@";;
  sync) server_rsync;;
  10) sweeb_expired_files "$@";;
  99) make-all;;
  rqc) find-no-rqc;;
  *) echo "Wrong selection";;
esac
