#!/usr/bin/env bash

# Author: Mohammed Albatati
# Date: 20251110
# Get the Asset details using fzf, I've created a file exporeted from sqlite database and I use this to
# fzf based on the file.
# Update: 20260130 I added the color options
# use flag -c to use the color output

set -e
# Ensure the asset csv file is available and if not then create it
[ ! -f "$HOME/org/Exported_database_2026_noes.csv" ] && echo 'File not available at temp directory  Creating a new csv file'

fzfAssets() {
  local color_enabled=false
  while getopts "c" opt; do
    case "$opt" in
    c) color_enabled=true ;;
    *)
      echo "Usage: $0 [-c]" >&2
      exit 1
      ;;
    esac
  done
  shift $((OPTIND - 1))

  local awk_format=""
  if "$color_enabled"; then
    awk_format='%-8s \033[35m%-20s\033[0m %-30s \033[33m%-20s\033[0m %-5s \033[34m%-10s\033[0m %-5s %-5s %-5s %-5s \033[36m%-5s\033[0m %-5s %-5s\n'
  else
    awk_format='%-8s %-12s %-20s %-20s %-5s %-10s %-5s %-5s %-5s %-5s %-5s %-5s %-5s\n'
  fi

  local fzf_opts="-m"
  if "$color_enabled"; then
    fzf_opts="-m --ansi"
  fi
  grepID=$(awk -F"," "{printf \"$awk_format\", \$1, \$2, \$3, \$4, \$5, \$6, \$7, \$8, \$9, \$10, \$11, \$12, \$13}" "/Users/mohammedalbatati/org/Exported_database_20251110.csv" | fzf $fzf_opts)
  echo "$grepID"
}
fzfAssets "$@"
